### ISSUE TITLE
Do i need an extra mod for ExtraDelight cause i cant do Sausage Rolls?

### ISSUE THREAD

**Issue by eywa-1706** [Lance5057/ExtraDelight#100]
I have some farmers delight mods including extra delight and here i cant do the sausage roll the bratwurst or the mac n' cheese with hot dogs. Mostly cause i nedd some kind of cooked sausage. Thats the writing over a mc barrier block. So do i need another mod to make it work.

2. question where the hell do i get vinegar from. I dont even get a recepie from just enough items and in theory in creative mod i can get it but how can i craft it?

**Comment by Lictor000** [comment]
There's many uncoockable recipes like these within the addon, asking for specific cuts of meat in the ingredient tag (I was trying the mod in 1.19.2,  version 1.3.3).
I guess it's something coming from butchercraft compatibility (which I did not try), but as it is it needs a fix.

**Comment by Lance5057** [comment]
Some recipes need butchercraft, vinegar comes from a vinegar pot
