### ISSUE TITLE
Pretty much every food in the 1.21.x version has an insane amount of saturation.

### ISSUE THREAD

**Issue by Gbergz** [Lance5057/ExtraDelight#101]
This is probably unintended if I were to guess. But worth to report.

Examples:
![ss](https://github.com/user-attachments/assets/a09887e8-882f-467f-af1e-e8885a7f0e81)

![ss2](https://github.com/user-attachments/assets/e885e623-a6ab-4928-9552-0806b854c2ac)

![ss3](https://github.com/user-attachments/assets/02e941ac-09cd-4c91-8383-a1c748cbe8f0)

MC 1.21.1
Using NeoForge 21.1.8
ExtraDelight: 2.0.1

**Comment by Lance5057** [comment]
They must have changed how saturation works, I'll look into it

**Comment by Corjo-Disblo** [comment]
Where can I download the fixed version of the mod? At the very least, the version on Curse Forge is still very much broken

**Comment by Lance5057** [comment]
It's not released yet, working on other fixes still

**Comment by Corjo-Disblo** [comment]
Ah, alright. Thanks for all your hard work
