### ISSUE TITLE
Drying Rack & Mortar Issues

### ISSUE THREAD

**Issue by fantA5q** [Lance5057/ExtraDelight#102]
Minecraft version: 1.21
Mod Loader: NeoForge 21.0.167
Extradelight version: 2.0.2
Placing items on the drying rack does not consume held items, so does the mortar.
For the drying rack: jerky can not be taken out by right-clicking the drying rack, and the only way is to break the drying rack.
![2024-08-20_08 24 09](https://github.com/user-attachments/assets/1b5b8413-26ac-4171-8411-0f0555d8cfdf)
![2024-08-20_08 24 20](https://github.com/user-attachments/assets/0866743d-e30a-4de8-bae9-9be79ff24207)

**Comment by Lance5057** [comment]
Thanks, I didn't catch that!

**Comment by sptriarius** [comment]
I'm also having this problem-- does it require an update on my end, or is something else needed? I'm using the most recent update for the mod.
