### ISSUE TITLE
Mortar only works once (0.3a)

### ISSUE THREAD

**Issue by ColonelPanic-Dev** [Lance5057/ExtraDelight#11]
Mortar recipes only work once, after that the items just disappear until you reload the game. The output even disappears from the JEI screen, you can see from this screenshot that I did the bonemeal and black dye recipes, but not the pink dye
![recipes](https://github.com/Lance5057/ExtraDelight/assets/134749686/36922686-46e6-4ea1-8f2d-0eac880d6042)

**Comment by Lance5057** [comment]
Do you have any other mods installed? I'm failing to reproduce this.

**Comment by ColonelPanic-Dev** [comment]
I'll keep testing. I can recreate the issue, but only in one particular area in one save game. The only other stuff around that location is some of the new create waterwheels and the elevator. I can't imagine anything like that is interfering but I'll see if I can narrow it down.

**Comment by ColonelPanic-Dev** [comment]
Ok, I have found a way to reliably replicate the issue
Forge 43.2.7
Mods:
Extra Delight 0.3a
Farmer's Delight 1.19-1.2.0

1. take the amethyst mortar and amethyst pestle
2. right click the mortar with a stack of bones, filling it
3. complete the recipe by using the pestle, but stand far enough away that you don't pick up the bone meal that pops out
4. several separate item stacks should pop out in different directions
5. wait a moment, all but one of those stacks will disappear
6. the recipe for bone meal will no longer work.

if this doesn't work the first time it only takes a couple attempts

**Comment by ColonelPanic-Dev** [comment]
singleplayer

**Comment by Lance5057** [comment]
Well I replicated it, now to figure out why...
