### ISSUE TITLE
Crash when placing Half Cabinet

### ISSUE THREAD

**Issue by EugeneLeclerc** [Lance5057/ExtraDelight#111]
The game crashes when I try to place a Half Cabinet.

Here is the crash report: [crash-2024-09-08_20.33.33-client.txt](https://github.com/user-attachments/files/16923289/crash-2024-09-08_20.33.33-client.txt)

I'm using Extra Delight latest version, 2.0.4.

I can provide more information if needed.

**Comment by Lance5057** [comment]
Are you playing this with fabric?

**Comment by EugeneLeclerc** [comment]
> Are you playing this with fabric?

The crash report I linked is from Neoforge but with Forgified Fabric API and Connector, so... half Fabric I guess ? 😄 

 Here is another crash report with absolutely nothing except Neoforge, Farmers Delight, and Extra Delight: [crash-2024-09-08_22.13.11-client.txt](https://github.com/user-attachments/files/16928532/crash-2024-09-08_22.13.11-client.txt)

**Comment by Lance5057** [comment]
hmm, my only guess is it's cause of 1.21.1? I can't replicate the issue in dev.
