### ISSUE TITLE
Can't play mod, immediate crash.

### ISSUE THREAD

**Issue by Anonymous6969696** [Lance5057/ExtraDelight#112]
Hey I'm playing the mod off of forge, and it keeps immediately crashing, not even letting me open the game.
![image_2024-09-08_144550692](https://github.com/user-attachments/assets/571b8b81-acc2-4bfb-a4e7-ef15d082c796)

It keeps saying there's an issue with the "Pie Block".

**Comment by Lance5057** [comment]
Please post a crash log

**Comment by Lance5057** [comment]
Seems you don't have Farmer's Delight due to curseforge missing a dependency, its been fixed on my end.
