### ISSUE TITLE
Bread Slice and Sliced Potato are not availabale

### ISSUE THREAD

**Issue by wr57atit** [Lance5057/ExtraDelight#114]
I created a new world with only Farmer's Delight and Extra Delight ; 
In this world Bread Slice and Sliced Potato are not available but all other cutting recipes can be done.
In my old world bread slice and Grated Potato are bad instead.
Here is the log if needed.
[minecraft-exported-logs-2024-09-16T00-35-35.log](https://github.com/user-attachments/files/17006535/minecraft-exported-logs-2024-09-16T00-35-35.log)

**Comment by wr57atit** [comment]
And there shows "perhaps another tool" when I'm cutting

**Comment by Lance5057** [comment]
Known issue with Farmer's Delight, waiting on a pr to go through
