### ISSUE TITLE
Client crash placing half-blocks

### ISSUE THREAD

**Issue by lmclarke** [Lance5057/ExtraDelight#136]
**Minecraft:** 1.21.1
**Version:** 2.0.4
**Platform:** NeoForge 21.1.73

Client crashes upon placing half-style blocks. Examples: half cabinet, spice rack.

**Comment by Lance5057** [comment]
Extra Delight version?

**Comment by lmclarke** [comment]
2.0.4

**Comment by Lance5057** [comment]
update to 2.1.1
