### ISSUE TITLE
corns have bugged texture

### ISSUE THREAD

**Issue by GlauberBlox** [Lance5057/ExtraDelight#147]
![image](https://github.com/user-attachments/assets/f11f5f72-e2ff-4dc2-afd4-50238b2b3b27)

1.21.1
mod ver 2.2.1

**Comment by Lance5057** [comment]
i dont see a bugged texture here

**Comment by JackNeksa** [comment]
It's random offset I guess?
Just like vanilla grass

**Comment by GlauberBlox** [comment]
btw if u want u can fix, i wont make you code hundred of lines just to fix something
this is just a texture bug, not a big problem

**Comment by Lance5057** [comment]
It's supposed to be offset? I'm so confused
