### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by RechercheRaptor** [Lance5057/ExtraDelight#18]
Probably just from the mod being on its first version and you may be aware of these already, but I thought I'd bring them up just in case.

Mixing bowl items can't be removed: If I right-click on a mixing bowl with the wrong item I can't get it back out again, and when I do properly mix ingredients I can't get those either. I've right-clicked and shift-right-clicked and nothing leaves the bowl. Also, non-food items can be placed in there by mistake, like a pestle.

Ovens don't show their baking progress: With furnaces, cooking pots, etc, there's a gray bar that fills up with white as the ingredients are converted into the product item. For ovens, this doesn't happen, and for a bit I thought the oven just wasn't working (I was trying to bake regular minecraft cookies in it), until it suddenly gave me my 8 cookies abruptly. Glad that it's working, but I wish there was visual confirmation of this.

Knife blocks and spice racks sometimes crashing when displaying some knives from other mods: Admittedly, this may be something to do with the other mods' item tagging, but I thought I may as well bring it up. Sometimes, another mod's knife (designed for Farmer's Delight compatibility) would crash my game if I tried putting it in a knife block or on display in a spice rack (thought I'd test that after the knife block weirdness). At different times, the Adamantite Knife from Enlightend and the Purpur Knife from End's Delight would cause crashes if I tried putting them in either display block, but other times, they would display perfectly fine.
When the launcher reopened, the error message it gave me would be something along these lines-
"The game crashed whilst container click
Error: java.lang.IndexOutOfBounds-" and then it would list an index number, and say it was too long a string. Unfortunately launcher error messages close quickly on macs, which is why I kept retrying some of the same knives, but now of course it's not crashing anymore.

I hope these reports are helpful, and don't just cause confusion :'] I love all of the ideas in this mod, the meals are more mouth-watering than any pixellated food has any right to be!

**Comment by Lance5057** [comment]
All of these errors have been fixed, just gotta finish a few more things to release.
