### ISSUE TITLE
Missing localization

### ISSUE THREAD

**Issue by MindFaer** [Lance5057/ExtraDelight#20]
The following items/blocks are missing proper names: sliced onions, sliced tomatoes, the beef, chicken, fish, rabbit, lamb, and pork rice stews, as well as the rice curry, the pork tenderloin sandwich, the cheese sandwich, the breadcrumbs, the breading misanplas, the bacon-egg sandwich, the bacon egg and cheese sandwich, the fish and chips, the buttered toast, the croutons, the salad and block of salad, alfredo sauce, the tomato pasta, the chicken parm, the cheeseburger and bacon cheeseburger, the riceball and filled riceball, the fish salad and fish salad sandwich, the chicken alfredo and alfredo pasta.

**Comment by Lance5057** [comment]
#13
