### ISSUE TITLE
Unknown recipe categories 0.5a

### ISSUE THREAD

**Issue by ColonelPanic-Dev** [Lance5057/ExtraDelight#23]
Looks like you've somehow inserted an extra "extradelight:" into your recipe names. I'm not sure if this breaks anything but you should check how you're handling these

>[20:53:21] [Render thread/WARN] [minecraft/ClientRecipeBook]: Unknown recipe category: extradelight:mortar/extradelight:mortar/green_dye
>[20:53:21] [Render thread/WARN] [minecraft/ClientRecipeBook]: Unknown recipe category: extradelight:mortar/extradelight:mortar/bone_meal
>[20:53:21] [Render thread/WARN] [minecraft/ClientRecipeBook]: Unknown recipe category: extradelight:feast/extradelight:lamb_stew_rice
>etc etc

**Comment by Lance5057** [comment]
This is, as far as I'm aware, a vanilla issue with the recipe book and not something I can fix.
