### ISSUE TITLE
Missing Translations (0.5a)

### ISSUE THREAD

**Issue by ColonelPanic-Dev** [Lance5057/ExtraDelight#28]
Just a couple left that I could find
![2023-06-08_21 29 08](https://github.com/Lance5057/ExtraDelight/assets/134749686/f4a89fb9-eed5-46ca-ab9d-03aece1e4a3e)
![2023-06-08_21 31 45](https://github.com/Lance5057/ExtraDelight/assets/134749686/8cb7dfb7-a6b4-4f80-9ab0-9b0f42fb5978)

**Comment by Lance5057** [comment]
Advancements are still WIP, forgot to hide those
