### ISSUE TITLE
Mod is completely broken.

### ISSUE THREAD

**Issue by shadoskill** [Lance5057/ExtraDelight#39]
![_2023-06-17_21-47-36](https://github.com/Lance5057/ExtraDelight/assets/640884/ca933f1b-d324-4cf6-83eb-af54e825911b)
In single player all recipes are unstack able nad get a nbt data applied to them.
On multiplayer, it causes no one to beable to join with the attached error.
Took a few hours to narrow it down but it is 100$ ExtraDelight. :C

**Comment by shadoskill** [comment]
Also to note, server produces no error besides client disconnected.
Client produces no extra info in the log.

Singleplayer shows no log errors.

**Comment by 00-Steven** [comment]
Refer to #40 for an explanation of the unstackable items problem.

Shown multiplayer issues _should_ be resolved as of writing, but not yet uploaded to curseforge/modrinth.
