### ISSUE TITLE
Drying rack has the same recipe as Butchercraft Drying Rack

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Lance5057/ExtraDelight#4]
I tried to right-click, left-click, and dropped items onto it, how do you use this block? 

version 0.3a

**Comment by ZephyrWindSpirit** [comment]
False alarm, I made the wrong item. Butchercraft and ExtraDelight have the same item recipe, and didn't realize it until I broke the block to look at it. Yours works fine.

**Comment by Lance5057** [comment]
Known issue, will be fixed when butchercraft updates
