### ISSUE TITLE
Extra nbt data on any crafted recipe? 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Lance5057/ExtraDelight#40]
I have spent a SOLID week off and on struggling to find out what has been causing this error. 
![2023-06-17_20 36 47](https://github.com/Lance5057/ExtraDelight/assets/16616656/7b8d0b3d-2ea8-4d28-8fb3-e9c257418c0e)
I have been using sticks as my check on this particular issue; A piece of nbt tag data cropping up on ANY crafted recipe. Planks, sticks, bowls of stew, you name it, it's there. Those crafted items **don't stack with any other set of sticks**. 
Now I see nothing in the logs, but when narrowing it down, this is the only mod in my cottagewitch modpack causing this error for me. 
Referencing #39 in a nicer format besides mod is completely broken. 

But this has been a source of great frustration and me pinning blame on several other mods in the meantime. Would be much appreciated if this would be fixed. I really would like to use your mod, but it also needs to have stackable items. Thank you!

extradelight 0.3a
Cottage Witch modpack 1.15.0, fresh download.

**Comment by 00-Steven** [comment]
Confirmed still an issue as of writing, seems to be an `OnCrafting` event for naming specific foods in `com.lance5057.extradelight.events.SetDynamicFoodName` causing the problem.
I'm presuming it's only supposed to work on items implementing `IDynamicNamedFood`, but it just calls a static method on the interface itself instead without checking for whether the item implements it.
This, of course, proceeds to cause this for every single crafting event. Commenting out the line seems to confirm this.

Shouldn't be too hard to fix though, at least.
