### ISSUE TITLE
Opening an oven with damaged baking tray inside crashes the game.

### ISSUE THREAD

**Issue by GreyMesmer** [Lance5057/ExtraDelight#46]
[crash-2023-06-30_15.06.53-client.txt](https://github.com/Lance5057/ExtraDelight/files/11916160/crash-2023-06-30_15.06.53-client.txt)

**Comment by belathus** [comment]
Yup, I got the same crash: https://gist.github.com/belathus/ce7f952f5db5134962f5718faea2760a

**Comment by Lance5057** [comment]
did you have the oven setup before the 0.6a update?
