### ISSUE TITLE
Can't craft mixing bowl 

### ISSUE THREAD

**Issue by MarshmallowFloof** [Lance5057/ExtraDelight#52]
One of the mods I use, uses the same recipe that the mixing bowl uses and therfore I cannot craft it. Not sure how to fix this or change it but I'm unable to use the mixing bowl or create it in any way as it just becomes the object from the other mod.

**Comment by RechercheRaptor** [comment]
Not sure if modders can do much for that, you might have to try out the Polymorph mod (lets you switch between results for crafting recipes shared by different mods)

**Comment by Lance5057** [comment]
not a mod problem, use a datapack or something like polymorph

**Comment by MarshmallowFloof** [comment]
Im sorry I didn't know that existed. But thanks for letting me know.
