### ISSUE TITLE
Can't get products out of mixing bowl

### ISSUE THREAD

**Issue by RechercheRaptor** [Lance5057/ExtraDelight#54]
I can remove ingredients by sneak-right-clicking before I mix them, but after they're mixed I can't get the products out. For example, when I mixed milk into cream, left-clicking, right-clicking, and sneak-right-clicking did nothing to get me the cream out of the bowl. The only way I've been able to get the cream is to break the mixing bowl entirely, which doesn't feel like an intended method.

**Comment by Lance5057** [comment]
you need to use a container item on it. whats required should be displayed on one of the corners of the bowl.
