### ISSUE TITLE
Bugs about mixing bowl and food display cabinet

### ISSUE THREAD

**Issue by HumulusQ** [Lance5057/ExtraDelight#55]
1.as others have reported, It seems like you can only break it to get the food once it is put into a mixing bowl, which is kind of annoying. And recipe cannot be identify "smartly": it takes 1 pasta and 1 tomato source to produce a tomato pasta ,however, if you put 4 tomato sauce and 4 pasta in, it wont automaticly pick up 1 of 4 to match the recipe. you'll have to TAKE OUT the rest.

2.In the case that the mixing bowl has already produced a piece of food. you are still allowed to put material into it, if you do the second mix process without takeout the first outcome. It will disappear, only one product remain.

3.The food display cabinet incorrectly displays part of the equipment bar in the player's item bar, so the food taken out may be placed in the equipment bar, while part of the item bar is not visible. I don't know if this bug is caused by other mods, but This does not happen to other containers of this mod (the part I have tried so far).

the version I am using is extradelight-0.6a

**Comment by Lance5057** [comment]
1. You can shift right click items out. Everything else works as intended.
2-3. Thats a bug oops.
