### ISSUE TITLE
Placing items does not consume the held item, and retrieving items duplicates items in the Drying Rack

### ISSUE THREAD

**Issue by smellyjoe** [Lance5057/ExtraDelight#58]
Hello Lance5057,
The Drying Rack from ExtraDelight duplicates items contained within it, and the Drying Rack does not consume the held item when placing ingredients into the Drying Rack (the same behavior occurs with Butchercraft's Drying Rack).

**Comment by Darkmega18** [comment]
I get this also. was LITERALLY about to post it.
