### ISSUE TITLE
Add compatability with ButcherCraft stock by selectively adding #forge:vegetables to #extradelight:makes_stock [Request]

### ISSUE THREAD

**Issue by wwhitfi7** [Lance5057/ExtraDelight#70]
ButcherCraft, another 1.19.x Farmer's Delight addon, has a different stock recipe which also accepts forge:vegetables. I re-enabled the ability to make stock by removing the #forge:vegetables tag from the makes_stock.json shipped in the mod's .jar file, but it shouldn't be too difficult to detect whether ButcherCraft is loaded and either remove vegetables from the makes_stock tag or load a different value for that tag.

I'm happy to work on this issue as well if it's not something that can be done right away.

**Comment by Lance5057** [comment]
Butchercraft stock is being removed in the next update.
