### ISSUE TITLE
[Request] Allow Mixing Bowl recipes to work even if "usedItem" is empty.

### ISSUE THREAD

**Issue by PineJamX** [Lance5057/ExtraDelight#72]
I am a Modpack maker and am trying to add a recipe for Mixing Bowl.

When adding a recipe for an item that does not have a visual container (such as Wheat Dough in Farmer's Delight), I would like to be able to retrieve the item with an empty hand after the mixing process is complete.
However, "usedItem" does not appear to be able to be emptied.

Is it technically possible to make the recipe work if the value of this "usedItem" is empty? (Like the "container" value in the cooking recipe in Farmer's Delight).

(I'm not an English speaker, so I'm not good at English.)

**Comment by Lance5057** [comment]
Mixing bowl will be getting an overhaul for 1.20, should fix this issue

**Comment by Lance5057** [comment]
This got fixed in the 1.2 update
