### ISSUE TITLE
Inventory Behavior inside GUI of Oven

### ISSUE THREAD

**Issue by SugarDaddii** [Lance5057/ExtraDelight#74]
![image](https://github.com/Lance5057/ExtraDelight/assets/14795020/61edd225-da96-4dd9-bfd7-e1acf1606ec9)
![image](https://github.com/Lance5057/ExtraDelight/assets/14795020/18a56612-40b1-4856-a2ad-ab858adb86ee)

The Inventory is sguffled when iam clicking inside the GUI of the Oven

**Comment by Zyrafosii** [comment]
Also experiencing this issue, using Forge version 43.3.5, Minecraft version 1.19.2, ExtraDelight version 1.1.8
