### ISSUE TITLE
Some issues with butchercraft

### ISSUE THREAD

**Issue by tealinecat** [Lance5057/ExtraDelight#76]
I use both extradelight and butchercraft, due to their abundance of items, some items appear twice, with different crafting recipes, or have different uses, such as: BBQ sauce, ketchup, gravy, cheese, butter, and some jelly. They confuse me while cooking, is there any way to combine them?

**Comment by tealinecat** [comment]
by the way：i use extradelight-1.1.8 and butchercraft-2.2.1 for 1.19.2

**Comment by Lance5057** [comment]
Known issue, will be fixed in next butchercraft update.
