### ISSUE TITLE
Tool priority on cutting board (0.3a)

### ISSUE THREAD

**Issue by ColonelPanic-Dev** [Lance5057/ExtraDelight#8]
Normally with the Farmer's Delight cutting board, you can put a stack of something in your offhand, and hold the tool in your main hand, and hold the right mouse button to process the whole stack, one by one. 

For example, you could hold a stack of cabbage in the off hand and the knife in the main hand, and by default the cabbage will be placed on the cutting board first, then the knife will cut it, and so on until  all the cabbage is done. Only then will the knife get placed on the board.

For some reason, your grater gets put on the cutting board first, so this process doesn't work

**Comment by Lance5057** [comment]
Had to remove the ability to place the grater as a block.

**Comment by ColonelPanic-Dev** [comment]
> Had to remove the ability to place the grater as a block.

oh no! That's kinda sad. Still, it'll look great in the spice rack
