### ISSUE TITLE
This mod causes the stock in Butchercraft to not be produced properly, resulting in a farmer's delight.

### ISSUE THREAD

**Issue by woshiruozhi233** [Lance5057/ExtraDelight#84]
Thank you for your efforts! Your module has great playability, but there is a strange bug here.
This mod causes the stock in Butchercraft to not be produced properly, resulting in a farmer's delight.
![Base Profile Screenshot 2023 12 27 - 07 45 17 85](https://github.com/Lance5057/ExtraDelight/assets/154936854/05661733-4011-4e81-8d36-917cd94cffa9)
![Base Profile Screenshot 2023 12 27 - 07 45 30 43](https://github.com/Lance5057/ExtraDelight/assets/154936854/d20aeba7-3c2c-4ab0-a8a8-a493bd0d774b)
If there is no extra delight, the stock in butchercraft can be successfully synthesized.
![Base Profile Screenshot 2023 12 27 - 07 56 31 33](https://github.com/Lance5057/ExtraDelight/assets/154936854/9d6c5150-aab3-4001-a4fb-a320a6d0c9b8)
![Base Profile Screenshot 2023 12 27 - 07 56 32 38](https://github.com/Lance5057/ExtraDelight/assets/154936854/4ff68530-18f7-41aa-89c9-2f7e3086be2b)

I don't know how to speak English.So I used software translation. If any useful words are not appropriate, please understand me
Finally, I want to tell you that I really like the mods you make, they are really fun!! I really like them!!!!

**Comment by Lance5057** [comment]
Butchercraft stock should be ignored, it'll be removed in the future.
