### ISSUE TITLE
Mint leaves spread rate needs to be drastically reduced.

### ISSUE THREAD

**Issue by Darkmega18** [Lance5057/ExtraDelight#92]
I have patches that over the span of an hour (in the base doing clean up, salvaging, building etc while on a server for myself and friends) can infest an entire area with the equivalent of several stacks of mostly useless mint leaves.
Please make them burnable as fuel or at the very least compostable cheaply as some way to get rid of them or DRASTICALLY reduce their spread rate. or better yet, don't have them spread at all except in large clusters when bonemealed potentially or all of the above.

These mint leaves are worse than an infestation mod. 

As an aside, the same goes for anything else you might add that potentially spreads or over spawns and is a fruit, crop, leaf or seed. It needs to be compostable if it isn't already.

**Comment by Darkmega18** [comment]
how much mint? 
![image](https://github.com/Lance5057/ExtraDelight/assets/8104689/425bb452-6e01-432a-8ac3-6f7cbc7a6b1a)
yes. I already dumped another half inventory in a lake somewhere.
and many more before that. please make it stop.

**Comment by Lance5057** [comment]
you can change it in configs

**Comment by Darkmega18** [comment]
given the defaults are this bad. you aughtta tweak the defaults down too then please.

**Comment by CounselorCloud** [comment]
> you can change it in configs

how does one do that on a server?

**Comment by zhua-w** [comment]
WTF????? 
![Image](https://github.com/user-attachments/assets/837d4533-d6f0-497d-b5fc-f2429038e1f2)

**Comment by zhua-w** [comment]
Why can't we just use something like mint seed? Mushrooms spread only in strict conditions, but mint? On dirt?

**Comment by Lance5057** [comment]
Do not reply to closed issues. The solution was given.
