### ISSUE TITLE
Sliced Bread conflict with Egg Delight's sliced bread

### ISSUE THREAD

**Issue by AdamElJefe** [Lance5057/ExtraDelight#94]
Running on 1.19.2, using the Farmer's Delight cutting board automatically defaults to the Egg Delight sliced bread.

Is there some kind of compatibility that can be made or is there a way to modify the IDs at all? Unfortunately using things like Polymorph don't really apply to the cutting board.

Any help or insight would be appreciated!

**Comment by Lance5057** [comment]
One of the mods would need to match the other's tag, assuming they have one.
Mine is:
`forge:bread/sliced`
Their mod is All Rights Reserved and they don't have an issue tracker so yeah nothing I can do on my side sorry.
